version: 2.1

orbs:
  psyplot: psyplot/psyplot-ci-orb@1.0.4

workflows:
  build-and-test:
    jobs:
      - psyplot/install-and-build
      - psyplot/build-docs:
          requires:
            - psyplot/install-and-build
