{% set name = "psy-simple" %}
{% set data = load_setup_py_data() %}

package:
  name: {{ name|lower }}
  version: {{ data.get('version') }}

source:
  git_url: ../../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{{ environ.get('CONDA_PY') }}_{{ environ.get('GIT_BUILD_STR', '') }}{% if environ.get('GIT_BRANCH') %}_{{ environ.get('GIT_BRANCH').replace('-', '') }}{% endif %}
  script: python -m pip install . --no-deps --ignore-installed -vvv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - psyplot

test:
  imports:
    - psy_simple
    - psy_simple.plotters

  requires:
    - pytest
    - pytest-cov
    - codecov
    - dask
    - pyqt
    - xarray
    - netCDF4
    - seaborn
  source_files:
    - tests

  commands:
    - pytest -sv --cov=psy_simple --ref --ignore=tests/widgets
    - py.test -sv --cov-append --cov=psy_simple --ignore=tests/widgets

about:
  home: https://github.com/Chilipp/psy-simple
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: Psyplot plugin for simple visualization tasks

  description: |
    This psyplot plugin provides plot methods for simple visualization tasks
    like 2D plots, line plots, bar plots, etc.
  doc_url: http://psyplot.readthedocs.io/projects/psy-simple
  dev_url: https://github.com/Chilipp/psy-simple
